name: 🐛 Bug Report
description: Report a bug that affects Lit or a Lit library/tool

body:
  - type: dropdown
    id: affected
    validations:
      required: true
    attributes:
      label: Which packages are you using?
      multiple: true
      description: Note you can select more than one.
      options:
        - Lit Core (lit/lit-html/reactive-element/lit-element)
        - Context (@lit-labs/context)
        - Eleventy Plugin (@lit-labs/eleventy-plugin-lit)
        - Localize (@lit/localize)
        - Motion (@lit-labs/motion)
        - Observers (@lit-labs/observers)
        - React (@lit-labs/react)
        - SSR (@lit-labs/ssr)
        - Starter Kits (@lit/lit-starter-(js|ts))
        - Task (@lit-labs/task)
        - Other/unknown

  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Which version are you using?
      description: Run e.g. `npm ls lit-element` to find the version you have installed.
      placeholder: 3.2.0

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      description: |
        What were you doing on the website or app when the bug happened? Detailed information helps maintainers reproduce and fix bugs.

        Issues filed without repro steps will be closed.
      placeholder: |
        Example bug report:
        1. Log in with username/password
        2. Click "Messages" on the left menu
        3. Open any message in the list

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Reproduction
      description: |
        Please link to a reproduction that will help us verify and understand the bug.

        For bugs that show up in the browser, please provide a link to the lit.dev playground: [TypeScript example](https://lit.dev/playground/#gist=b90fc1b4d2ee57120763d2e7db934511), [JavaScript example](https://lit.dev/playground/#gist=2d20e91832d3f98332bf23ced55bea04).
        Click the "Share" button to generate a URL.

        For bugs that show up on the command-line, please create a public GitHub repo, and provide step-by-step instructions for cloning, installing, building, running, and observing the bug.
      placeholder: |
        The text should update when the button is clicked, but it doesn't:
        https://lit.dev/playground/#gist=b90fc1b4d2ee57120763d2e7db934511

        1. git clone git@github.com:<user>/<repo>.git
        2. cd <repo>
        3. npm ci
        4. npm run serve
        5. ...

  - type: textarea
    id: workaround
    validations:
      required: false
    attributes:
      label: Around
