name: Bug Report
description: Report a bug that affects Lit or a Lit library/tool

body:
  - type: dropdown
    id: affected
    attributes:
      label: Which @angular/* package(s) are the source of the bug?
      options:
        - lit/lit-html/reactive-element/lit-element
        - Starter Kits
        - @lit/localize
        - @lit-labs/ssr
        - @lit-labs/eleventy-plugin-lit
        - @lit-labs/context
        - @lit-labs/react
        - @lit-labs/observers
        - @lit-labs/motion
        - @lit-labs/task
        - Other
      multiple: true
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Please provide a link to a minimal reproduction of the bug
