name: 🐛 Bug Report
description: Report a bug that affects Lit or a Lit library/tool

body:
  - type: dropdown
    id: affected
    validations:
      required: true
    attributes:
      label: Which packages are affected?
      options:
        - lit/lit-html/reactive-element/lit-element
        - Starter Kits
        - '@lit/localize'
        - '@lit-labs/ssr'
        - '@lit-labs/eleventy-plugin-lit'
        - '@lit-labs/context'
        - '@lit-labs/react'
        - '@lit-labs/observers'
        - '@lit-labs/motion'
        - '@lit-labs/task'
        - Other/unknown
      multiple: true

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Please provide a link to a minimal reproduction of the bug
    placeholder: |
      Example bug report:
      1. Log in with username/password
      2. Click "Messages" on the left menu
      3. Open any message in the list

  - type: textarea
    id: workaround
    validations:
      required: false
    attributes:
      label: Around
