name: 🐛 Bug Report
description: Report a bug that affects Lit or a Lit library/tool

body:
  - type: dropdown
    id: affected
    validations:
      required: true
    attributes:
      label: Which packages are affected?
      options:
        - lit/lit-html/reactive-element/lit-element
        - Starter Kits
        - '@lit/localize'
        - '@lit-labs/ssr'
        - '@lit-labs/eleventy-plugin-lit'
        - '@lit-labs/context'
        - '@lit-labs/react'
        - '@lit-labs/observers'
        - '@lit-labs/motion'
        - '@lit-labs/task'
        - Other/unknown
      multiple: true

  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Which version are you using?
      placeholder: 3.2.0

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      description: |
        What were you doing on the website or app when the bug happened? Detailed information helps maintainers reproduce and fix bugs.

        Issues filed without repro steps will be closed.
      placeholder: |
        Example bug report:
        1. Log in with username/password
        2. Click "Messages" on the left menu
        3. Open any message in the list

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Reproduction
      placeholder: |
        TypeScript: https://lit.dev/playground/#gist=b90fc1b4d2ee57120763d2e7db934511
        JavaScript: https://lit.dev/playground/#gist=2d20e91832d3f98332bf23ced55bea04

  - type: textarea
    id: workaround
    validations:
      required: false
    attributes:
      label: Around
