name: 🐛 Bug Report
description: Report a bug that affects Lit or a Lit library/tool

body:
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      description: |
        Please describe the bug in as much detail as possible. Include what you expected to happen, and what actually happened. If you have an error message, please include as much of the error message as possible.
      placeholder: |
        When I use the foo API, I get the following error.

  - type: dropdown
    id: affected
    validations:
      required: true
    attributes:
      label: Which package(s) are affected?
      multiple: true
      description: Note you can select more than one.
      options:
        - Lit Core (lit/lit-html/reactive-element/lit-element)
        - Context (@lit-labs/context)
        - Eleventy Plugin (@lit-labs/eleventy-plugin-lit)
        - Localize (@lit/localize)
        - Motion (@lit-labs/motion)
        - Observers (@lit-labs/observers)
        - React (@lit-labs/react)
        - SSR (@lit-labs/ssr)
        - Starter Kits (@lit/lit-starter-(js|ts))
        - Task (@lit-labs/task)
        - Other/unknown

  - type: dropdown
    id: regression
    validations:
      required: true
    attributes:
      label: Is this a regression?
      multiple: false
      options:
        - Yes. This used to work, but now it doesn't.
        - No/unsure. This never worked, or I haven't tried before.

  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Affected versions
      description: What version are you using, and if this is a known regression, what is the last known version that worked? Run e.g. `npm ls lit` to check your installed version.
      placeholder: |
        Failing in 3.2.0, worked in 3.1.0

  - type: textarea
    id: environment
    validations:
      required: true
    attributes:
      label: Description
      description: |
        Please describe the bug in as much detail as possible. Include what you expected to happen, and what actually happened. If you have an error message, please include as much of the error message as possible.
      placeholder: |
        Chrome 103.0.5060.53

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Reproduction
      description: |
        Please link to a working reproduction that will help us verify and understand the bug.

        For bugs that show up in the browser, please provide a link to the lit.dev playground: [TypeScript example](https://lit.dev/playground/#gist=b90fc1b4d2ee57120763d2e7db934511), [JavaScript example](https://lit.dev/playground/#gist=2d20e91832d3f98332bf23ced55bea04). Click the "Share" button to generate a URL.

        For bugs that show up on the command-line, please create a public GitHub repo, and provide step-by-step instructions for cloning, setting up, and observing the bug.
      placeholder: |
        The text should update when the button is clicked, but it doesn't:
        https://lit.dev/playground/#gist=b90fc1b4d2ee57120763d2e7db934511

        ... or for command-line issues:

        1. git clone git@github.com:<user>/<repo>.git
        2. cd <repo>
        3. npm ci
        4. npm run serve
        5. Observe the error "Error: Cannot do something"

  - type: textarea
    id: workaround
    validations:
      required: true
    attributes:
      label: Workaround
      description: |
        If you have found a workaround for this problem, please explain it here. If you have not found a workaround, please say so here.
      placeholder: |
        I have worked around this problem by using the foo API instead of the bar API.

        ... or:

        I have not found a workaround.
